version: '3.9'

services:
  temporal:
    image: temporalio/auto-setup:1.25.1
    environment:
      - TEMPORAL_UI_PORT=8233
      - TEMPORAL_GRPC_PORT=7233
    ports:
      - "7233:7233"
      - "8233:8233"

  temporal-admin-tools:
    image: temporalio/admin-tools:1.25.1
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    entrypoint: /bin/sh -c 'sleep infinity'

  temporal-ui:
    image: temporalio/ui:2.30.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    ports:
      - "8088:8080"
