spring:
  application:
    name: temporal-agents
  ai:
    openai:
      api-key: ${LLM_KEY:}
      base-url: ${LLM_BASE_URL:}
      chat:
        options:
          model: ${LLM_MODEL:gpt-4o-mini}
          temperature: 0.2

pandadoc:
  api-key: ${PANDADOC_API_KEY:}
  base-url: ${PANDADOC_BASE_URL:https://api.pandadoc.com/public/v1}
  status-check-interval-seconds: ${PANDADOC_STATUS_INTERVAL:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info

temporal:
  address: ${TEMPORAL_ADDRESS:localhost:7233}
  namespace: ${TEMPORAL_NAMESPACE:default}
  task-queue: ${TEMPORAL_TASK_QUEUE:agent-task-queue}
